[pytest]
pythonpath = .
testpaths = tests
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning:flask_sqlalchemy.query
    ignore::DeprecationWarning:sqlalchemy.orm.query
    ignore::sqlalchemy.exc.SAWarning