[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:flask_sqlalchemy.query
    ignore::DeprecationWarning:sqlalchemy.orm.query
    ignore::sqlalchemy.exc.SAWarning