"""replace token with pin

Revision ID: bfe45b7df852
Revises: 9bc831186602
Create Date: 2026-03-23 09:48:52.177091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe45b7df852'
down_revision = '9bc831186602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competence', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_competence_nom', ['nom'])

    with op.batch_alter_table('entretien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=200), nullable=True))
        batch_op.alter_column('date_entretien',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('token_recruteur2')

    with op.batch_alter_table('poste', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_poste_nom', ['nom'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poste', schema=None) as batch_op:
        batch_op.drop_constraint('uq_poste_nom', type_='unique')

    with op.batch_alter_table('entretien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_recruteur2', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('date_entretien',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('pin_hash')

    with op.batch_alter_table('competence', schema=None) as batch_op:
        batch_op.drop_constraint('uq_competence_nom', type_='unique')

    # ### end Alembic commands ###
